---
- name: Ensure that the rssh package is installed
  tags: rssh
  become: true
  package:
    name: rssh
    state: present

- name: Attempting to inject /usr/bin/rssh into /etc/shells
  tags: rssh
  become: true
  lineinfile:
    dest: /etc/shells
    line: /usr/bin/rssh
    owner: root
    group: root
    mode: 0644

- name: Attempting to overlay rssh configurations
  tags: rssh
  become: true
  template:
    src: rssh.conf.j2
    dest: /etc/rssh.conf
    owner: root
    group: root
    mode: 0644

- name: Attempting to apply group configurations
  tags: rssh
  become: true
  no_log: true
  group:
    gid: "{{ item.gid|default(omit) }}"
    name: "{{ item.group|default(item.name) }}"
    state: "{{ item.state|default('present') }}"
    system: "{{ item.system|default('no') }}"
  loop: "{{ rssh_users }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.name is defined
    - rssh_users|length > 0

- name: Attempting to apply user configurations
  tags: rssh
  become: true
  user:
    append: "{{ item.append|default('no') }}"
    comment: "{{ item.comment|default(item.name) }}"
    createhome: "{{ item.createhome|default(omit) }}"
    generate_ssh_key: "{{ item.generate_ssh_key|default('no') }}"
    group: "{{ item.group|default(item.name) }}"
    groups: rsshusers
    home: "{{ item.path + '/home/' + item.name if item.path is defined else omit }}"
    local: "{{ item.local|default(omit) }}"
    login_class: "{{ item.login_class|default(omit) }}"
    move_home: "{{ item.move_home|default('no') }}"
    name: "{{ item.name }}"
    non_unique: "{{ item.non_unique|default('no') }}"
    password: "{{ item.password|default('!!') }}"
    seuser: "{{ item.seuser|default(omit) }}"
    shell: /usr/bin/rssh
    skeleton: "{{ item.skeleton|default(omit) }}"
    ssh_key_bits: "{{ item.ssh_key_bits|default(omit) }}"
    ssh_key_comment: "{{ item.ssh_key_comment|default(item.name) }}"
    ssh_key_file: "{{ item.ssh_key_file|default(omit) }}"
    ssh_key_passphrase: "{{ item.ssh_key_passphrase|default(omit) }}"
    ssh_key_type: "{{ item.ssh_key_type|default(omit) }}"
    state: "{{ item.state|default('present') }}"
    system: "{{ item.system|default('no') }}"
    uid: "{{ item.uid|default(omit) }}"
    update_password: "{{ item.update_password|default('always') }}"
  loop: "{{ rssh_users }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.name is defined
    - rssh_users|length > 0
...
